Traceback (most recent call last):
  File "/net/tscratch/people/plgmpniak/KITS_project/Kits_23/kits23/kits23/preprocessing/kidney_preprocessing.py", line 64, in <module>
    main()
  File "/net/tscratch/people/plgmpniak/KITS_project/Kits_23/kits23/kits23/preprocessing/kidney_preprocessing.py", line 50, in main
    raise ValueError(f"Liczba przypadków ({len(all_cases)}) musi być większa niż 489, aby utworzyć zbiór testowy.")
ValueError: Liczba przypadków (489) musi być większa niż 489, aby utworzyć zbiór testowy.
