Processing → /net/tscratch/people/plgmpniak/KITS_project/Kits_23/data/augmented_data/train:   0%|          | 0/391 [00:00<?, ?it/s]Processing → /net/tscratch/people/plgmpniak/KITS_project/Kits_23/data/augmented_data/train:   0%|          | 0/391 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/net/tscratch/people/plgmpniak/miniconda3/envs/kits23-augment/lib/python3.10/site-packages/monai/transforms/transform.py", line 150, in apply_transform
    return _apply_transform(transform, data, unpack_items, lazy, overrides, log_stats)
  File "/net/tscratch/people/plgmpniak/miniconda3/envs/kits23-augment/lib/python3.10/site-packages/monai/transforms/transform.py", line 98, in _apply_transform
    return transform(data, lazy=lazy) if isinstance(transform, LazyTrait) else transform(data)
  File "/net/tscratch/people/plgmpniak/miniconda3/envs/kits23-augment/lib/python3.10/site-packages/monai/transforms/utility/dictionary.py", line 277, in __call__
    d[key] = self.adjuster(d[key], meta_dict)
  File "/net/tscratch/people/plgmpniak/miniconda3/envs/kits23-augment/lib/python3.10/site-packages/monai/transforms/utility/array.py", line 204, in __call__
    raise ValueError(msg)
ValueError: Metadata not available and channel_dim=None, EnsureChannelFirst is not in use.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/net/tscratch/people/plgmpniak/KITS_project/Kits_23/preprocessing/data_augumentation.py", line 66, in <module>
    augment_and_save(train_files, train_dir, train_transform)
  File "/net/tscratch/people/plgmpniak/KITS_project/Kits_23/preprocessing/data_augumentation.py", line 61, in augment_and_save
    sample = transform(sample)
  File "/net/tscratch/people/plgmpniak/miniconda3/envs/kits23-augment/lib/python3.10/site-packages/monai/transforms/compose.py", line 346, in __call__
    result = execute_compose(
  File "/net/tscratch/people/plgmpniak/miniconda3/envs/kits23-augment/lib/python3.10/site-packages/monai/transforms/compose.py", line 116, in execute_compose
    data = apply_transform(
  File "/net/tscratch/people/plgmpniak/miniconda3/envs/kits23-augment/lib/python3.10/site-packages/monai/transforms/transform.py", line 180, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.utility.dictionary.EnsureChannelFirstd object at 0x14d2ed6d7340>
